language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - nightly
sudo: required

services: postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE=djClassSchedule.settings
    - DEBUG=on
    - SECRET_KEY=not-so-secret
    - DATABASE_URL=postgres://postgres@localhost:5432/mydb
    - CACHE_URL=locmemcache://
    - SEARCH_URL=simple://
    - BANNER_CONNECTION_URL=$USER@localhost:1521/

    - ORACLE_COOKIE=sqldev
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE
    - PATH=$PATH:$ORACLE_HOME/bin
    - LD_LIBRARY_PATH=$ORACLE_HOME/lib
    - NLS_LANG=American_America.UTF8
  matrix:
    - DJANGO_VERSION=1.11

# command to install dependencies
install:
  # Install Oracle
  - wget 'https://github.com/cbandy/travis-oracle/archive/v2.0.2.tar.gz'
  - mkdir -p .travis/oracle
  - tar x -C .travis/oracle --strip-components=1 -f v2.0.2.tar.gz
  - .travis/oracle/download.sh
  - .travis/oracle/install.sh

  - pip install -r requirements.txt
  - pip install django==$DJANGO_VERSION --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py migrate --noinput
  - python manage.py test