language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - nightly

services: postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE=djClassSchedule.settings
    - DEBUG=on
    - SECRET_KEY=not-so-secret
    - DATABASE_URL=postgres://postgres:@localhost:5432/travisci
    - CACHE_URL=locmemcache://
    - SEARCH_URL=simple://
    - BANNER_CONNECTION_URL=username/pass@bannerurl:port/databaseID
    - PIP_USE_MIRRORS=true
  matrix:
    - DJANGO_VERSION=1.11

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO_VERSION --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py migrate --noinput
  - python manage.py test